openapi: 3.0.1
info:
  title: Process Instance related API
  description: See details following.
  version: '7.11'
servers:
  - url: 'https://bpez.eorionsolution.com/engine-rest'
components:
  schemas:
    ProcessInstance:
      title: process instance objects
      type: object
      properties:
        id:
          type: string
          description: The id of the process instance.
        definitionId:
          type: string
          description: The id of the process definition that this process instance belongs to.
        businessKey:
          type: string
          description: The business key of the process instance.
        caseInstanceId:
          type: string
          description: The id of the case instance associated with the process instance.
        ended:
          type: boolean
          description: A flag indicating whether the process instance has ended or not. But it will always be false!
          default: false
          deprecated: true
        suspended:
          type: boolean
          description: A flag indicating whether the process instance is suspended or not.
        tenantId:
          type: string
          description: The tenant id of the process instance.
paths:
  /process-instance:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      operationId: getProcessInstaces
      responses:
        '200':
          description: OK
